//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroTransport
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAmount
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public int Count { get; set; }
    
        public virtual Transport Transport { get; set; }
    }
}
